config/routes.rb
Rails.application.routes.draw do
  get '/login',     to: "sessions#new"
  post '/login',    to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  namespace :admin do
    resources :categories, only: [:new, :create, :index, :destroy]
    resources :images, only: [:index, :new, :create, :destroy]
  end

  resources :users, only: [:new, :create, :show, :destroy] do
    resources :ideas
  end

  resources :images, only: [:index]

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

    has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :idea_images
  has_many :images, through: :idea_images

  validates :title, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true

  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  enum role: ["user", "admin"]

  has_many :ideas

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "#{@category.name} created!"
      redirect_to admin_categories_path
    else
      flash[:notice] = "Name must be filled in"
      render new_admin_category_path
    end
  end

  def index
    @categories = Category.all
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:notice] = "#{category.name} deleted"

    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    image = Image.new(image_params)
    if image.save
      flash[:notice] = "#{image.name} added!"
      redirect_to admin_images_path
    else
      render :new
    end
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    flash[:notice] = "#{image.name} deleted"

    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:name, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :check_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_current_user
    render file: "/public/404" unless current_user
  end

  # def check_user
  #   if current_user.id != params[:user_id].to_i
  #     render file: "/public/404"
  #   else
  #   end
  # end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @idea = @user.ideas.new
    @images = Image.all
  end

  def create
    user = User.find(params[:user_id])
    @idea = user.ideas.new(idea_params)
    if @idea.save
      flash[:notice] = "Idea created!"
      redirect_to user_path(user)
    else
      flash[:notice] = "All fields must be filled in"
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)

    flash[:notice] = "#{@idea.title} updated!"

    redirect_to user_idea_path(@idea.user, @idea)
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    redirect_to user_path(@idea.user)
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :category_id, image_ids:[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successful login"
      redirect_to user_path(@user)
    else
      flash[:notice] = "Invalid Credentials"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user, except: [:new, :create]
  #before_action :check_user, except: [:new, :create]
  #skip_before_action :require_current_user, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Successful login"
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  def destroy
    @user = User.find(params[:id])
    session.clear
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/index.html.erb
<h1>Categories Index</h1>

<ul>
<% @categories.each do |category| %>
  <li><%= category.name %> - <%= link_to "Delete", admin_category_path(category), method: :delete %></li>
<% end %>
</ul>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: 'form' %>

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Add Image" %>
<% end %>

app/views/admin/images/index.html.erb
<h1>Images Index</h1>
<ul>
<% @images.each do |image| %>
  <li><%= image.name %> <img src="<%= image.url %>" alt="light bulb"> <%= link_to "Delete", admin_image_path(image), method: :delete %></li>

<% end %>
</ul>
<%= link_to "New Image", new_admin_image_path  %>

app/views/admin/images/new.html.erb
<h1>New Image</h1>

<%= render partial: 'form' %>

app/views/ideas/_form.html.erb
<%= form_for [@idea.user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: 'Select Category', required: true) %>
  <%= f.collection_check_boxes :image_ids, Image.all, :id, :name do |b| %>
    <%= b.check_box %>
    <%= b.label %>
  <% end %>
  
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render partial: 'form' %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render partial: 'form' %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>

<% @idea.images.each do |image| %>
  <img src="<%= image.url %>" alt="">
<% end %>

<p><%= @idea.description %></p>
<p>Category: <%= @idea.category.name %></p>
<%= link_to "Select Image", edit_user_idea_path(@idea.user, @idea) %>
<%= link_to "Edit", edit_user_idea_path(@idea.user, @idea) %>
<%= link_to "Delete", user_idea_path(@idea.user, @idea), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% flash.each do |type, message| %>
        <%= content_tag :div, message, class: "flash_#{type}" %>
      <% end %>
      <% if current_user %>
          Welcome, <%= current_user.username %>
          <%= link_to "Logout", logout_path, method: :delete %>
          <%= link_to "Close Account", user_path(current_user), method: :delete %>
        <% else %>
          <%= link_to "User Login", login_path %>
        <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>User's Show Page</h1>
<h2>Welcome, <%= @user.username %></h2>

<ol>
  <% @user.ideas.each do |idea| %>
    <li><%= link_to idea.title, user_idea_path(@user, idea) %></li>
  <% end %>
</ol>

<%= link_to "New Idea", new_user_idea_path(@user) %>

app/views/welcome/index.html.erb
<h1>Welcome Index</h1>